# Лабораторная работа #5
### Варламов Никита, М33361; Гайнанов Ильдар, М33371;

In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv('cars93.csv')
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city   
0         Acura  Integra    Small       12.9   15.9       18.8        25  \
1         Acura   Legend  Midsize       29.2   33.9       38.7        18   
2          Audi       90  Compact       25.9   29.1       32.3        20   
3          Audi      100  Midsize       30.8   37.7       44.6        19   
4           BMW     535i  Midsize       23.7   30.0       36.2        22   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7        17   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4        21   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7        18   
91        Volvo      240  Compact       21.8   22.7       23.5        21   
92        Volvo      850  Midsize       24.8   26.7       28.5        20   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length   
0            31                 NaN      Front  ...          5     177  \
1            25  Driver & Passenger      Front  ...          5     195   
2            26         Driver only      Front  ...          5     180   
3            26  Driver & Passenger      Front  ...          6     193   
4            30         Driver only       Rear  ...          4     186   
..          ...                 ...        ...  ...        ...     ...   
88           21                 NaN      Front  ...          7     187   
89           30                 NaN      Front  ...          5     180   
90           25                 NaN      Front  ...          4     159   
91           28         Driver only       Rear  ...          5     190   
92           28  Driver & Passenger      Front  ...          5     184   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight   
0         102     68           37           26.5          11.0    2705  \
1         115     71           38           30.0          15.0    3560   
2         102     67           37           28.0          14.0    3375   
3         106     70           37           31.0          17.0    3405   
4         109     69           39           27.0          13.0    3640   
..        ...    ...          ...            ...           ...     ...   
88        115     72           38           34.0           NaN    3960   
89        103     67           35           31.5          14.0    2985   
90         97     66           36           26.0          15.0    2810   
91        104     67           37           29.5          14.0    2985   
92        105     69           38           30.0          15.0    3245   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88  non-USA  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [3]:
city = np.array(df['MPG.city'])
highway = np.array(df['MPG.highway'])
horsepower = np.array(df['Horsepower'])
free_coeff = np.ones(city.shape)
price = np.array(df['Price'])[:, np.newaxis]
X = np.array([free_coeff, city, highway, horsepower]).T

price

array([[15.9],
       [33.9],
       [29.1],
       [37.7],
       [30. ],
       [15.7],
       [20.8],
       [23.7],
       [26.3],
       [34.7],
       [40.1],
       [13.4],
       [11.4],
       [15.1],
       [15.9],
       [16.3],
       [16.6],
       [18.8],
       [38. ],
       [18.4],
       [15.8],
       [29.5],
       [ 9.2],
       [11.3],
       [13.3],
       [19. ],
       [15.6],
       [25.8],
       [12.2],
       [19.3],
       [ 7.4],
       [10.1],
       [11.3],
       [15.9],
       [14. ],
       [19.9],
       [20.2],
       [20.9],
       [ 8.4],
       [12.5],
       [19.8],
       [12.1],
       [17.5],
       [ 8. ],
       [10. ],
       [10. ],
       [13.9],
       [47.9],
       [28. ],
       [35.2],
       [34.3],
       [36.1],
       [ 8.3],
       [11.6],
       [16.5],
       [19.1],
       [32.5],
       [31.9],
       [61.9],
       [14.1],
       [14.9],
       [10.3],
       [26.1],
       [11.8],
       [15.7],
       [19.1],
       [21

In [4]:
coef_matrix = np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), price)
print(f'Коэффициенты по формуле {coef_matrix.T[0]}')

Коэффициенты по формуле [ 6.68867892 -0.03860018 -0.17885863  0.13131383]


In [5]:
from sklearn.linear_model import LinearRegression

#проверим расчет используя библиотеку sklearn
model = LinearRegression().fit(X, price)
coef_sklearn = model.coef_.T
coef_sklearn[0] = model.intercept_
print(f'Коэффициенты sklearn {coef_sklearn.T[0]}')

Коэффициенты sklearn [ 6.68867892 -0.03860018 -0.17885863  0.13131383]


In [6]:
coef_matrix

array([[ 6.68867892],
       [-0.03860018],
       [-0.17885863],
       [ 0.13131383]])

Посчитаем остаточную дисперсию:

In [7]:
np.dot(coef_matrix.T[0], X[92])
price

array([[15.9],
       [33.9],
       [29.1],
       [37.7],
       [30. ],
       [15.7],
       [20.8],
       [23.7],
       [26.3],
       [34.7],
       [40.1],
       [13.4],
       [11.4],
       [15.1],
       [15.9],
       [16.3],
       [16.6],
       [18.8],
       [38. ],
       [18.4],
       [15.8],
       [29.5],
       [ 9.2],
       [11.3],
       [13.3],
       [19. ],
       [15.6],
       [25.8],
       [12.2],
       [19.3],
       [ 7.4],
       [10.1],
       [11.3],
       [15.9],
       [14. ],
       [19.9],
       [20.2],
       [20.9],
       [ 8.4],
       [12.5],
       [19.8],
       [12.1],
       [17.5],
       [ 8. ],
       [10. ],
       [10. ],
       [13.9],
       [47.9],
       [28. ],
       [35.2],
       [34.3],
       [36.1],
       [ 8.3],
       [11.6],
       [16.5],
       [19.1],
       [32.5],
       [31.9],
       [61.9],
       [14.1],
       [14.9],
       [10.3],
       [26.1],
       [11.8],
       [15.7],
       [19.1],
       [21

In [8]:
def f(coeff, X):
    return np.dot(coeff, X)

predicted_price = []
for i in range(X.shape[0]):
    predicted_price.append(f(coef_matrix.T[0], X[i]))

predicted_price = np.array(predicted_price)
predicted_price

array([18.56299351, 27.78517645, 23.85233016, 23.89093034, 27.78699325,
       14.73937908, 23.27058543, 25.23610016, 23.44944405, 27.86237681,
       40.33719085, 13.72928541, 14.08700267, 21.9574471 , 15.13569652,
       24.20347874, 24.199286  , 23.70550304, 40.95515983, 20.9996501 ,
       19.30808358, 20.56948436, 11.7478116 , 12.82616101, 14.14167527,
       20.92300887, 14.18027545, 41.09541828, 11.7478116 , 29.00979386,
        7.86251011, 17.11197268, 13.61641994, 14.44052718, 15.49760651,
       21.57300935, 18.89625285, 26.2931795 ,  3.19240012, 10.91000788,
       21.22787033, 10.23398545, 18.60159369, 10.30335945, 16.93548999,
       11.68475351, 17.89566293, 38.60283141, 25.99432759, 31.4257395 ,
       22.39236472, 28.91945614,  9.71923877, 12.69428805, 21.13934942,
       22.05491263, 35.04603739, 17.80057334, 29.97891141, 14.28193372,
       19.68888772, 11.7478116 , 28.22666274, 14.11146058, 20.09359064,
       21.74711611, 22.237964  , 20.57130117, 14.7007789 , 24.20

In [9]:
var = np.var(price - predicted_price)

In [10]:
var

150.44317796119884

In [11]:
price

array([[15.9],
       [33.9],
       [29.1],
       [37.7],
       [30. ],
       [15.7],
       [20.8],
       [23.7],
       [26.3],
       [34.7],
       [40.1],
       [13.4],
       [11.4],
       [15.1],
       [15.9],
       [16.3],
       [16.6],
       [18.8],
       [38. ],
       [18.4],
       [15.8],
       [29.5],
       [ 9.2],
       [11.3],
       [13.3],
       [19. ],
       [15.6],
       [25.8],
       [12.2],
       [19.3],
       [ 7.4],
       [10.1],
       [11.3],
       [15.9],
       [14. ],
       [19.9],
       [20.2],
       [20.9],
       [ 8.4],
       [12.5],
       [19.8],
       [12.1],
       [17.5],
       [ 8. ],
       [10. ],
       [10. ],
       [13.9],
       [47.9],
       [28. ],
       [35.2],
       [34.3],
       [36.1],
       [ 8.3],
       [11.6],
       [16.5],
       [19.1],
       [32.5],
       [31.9],
       [61.9],
       [14.1],
       [14.9],
       [10.3],
       [26.1],
       [11.8],
       [15.7],
       [19.1],
       [21

In [12]:
from sklearn.metrics import r2_score

print("r2_score", r2_score(predicted_price, price))

r2_score 0.41248143168929163


#### Доверительный интервал для коэффициентов. 
Учитывая, что на лекции доказывалось, что:
![image](st1.png)

Можно вывести (по определению доверительного интервала):
$P\left(-t_{1-\frac{\alpha}{2}} \le \frac{c^T(\hat{\theta}_j - \theta_j)}{\hat{\sigma}\sqrt{c^T(X^TX)^{-1}_{jj}}c} \le t_{1-\frac{\alpha}{2}}\right) = 1 - \alpha$

$\hat{\theta_j} - t_{1-\frac{\alpha}{2}} \cdot \hat{\sigma}\sqrt{(X^TX)^{-1}_{jj}} \le \theta_j \le \hat{\theta_j} + t_{1-\frac{\alpha}{2}} \cdot \hat{\sigma}\sqrt{(X^TX)^{-1}_{jj}}$

In [13]:
from scipy.stats import t

n = X.shape[0] # количество выборок
k = coef_matrix.T[0].size # количество коэффициентов
alpha = 0.05

quantile = t.ppf(1 - alpha / 2, n - k)
quantile

1.9869786993737677

In [14]:
def rss(X, y):
    return np.sum((X - y) ** 2)

In [15]:
rss(predicted_price, price)

1301183.0461864087

In [16]:
sigma = np.sqrt(rss(predicted_price, price) / (n - k))
sigma

120.91333353610585

In [17]:
xtx = np.linalg.inv(np.dot(X.T, X))

def get_j(j):
    return sigma * xtx[j][j]

theta_hat = coef_matrix.T[0]

theta_result_left = []
theta_result_right = []

def se(q, j):
    return q * get_j(j)

for i in range(4):
    theta_result_left.append(theta_hat[i] - se(quantile, i))
    theta_result_right.append(theta_hat[i] + se(quantile, i))
    
theta_result_left = np.array(theta_result_left)
theta_result_right = np.array(theta_result_right)

In [18]:
theta_result_left # левая граница

array([-2.34684983e+02, -8.96841616e-01, -1.02533683e+00,  1.29567815e-01])

In [19]:
theta_result_right # правая граница

array([2.48062341e+02, 8.19641259e-01, 6.67619580e-01, 1.33059850e-01])

Для дисперсии же:

![image](khi2.png)

Тогда доверительный интервал: 
$\frac{RSS}{\chi^2_{\frac{\alpha}{2}}} \le \sigma^2 \le \frac{RSS}{\chi^2_{1-\frac{\alpha}{2}}}$

In [20]:
from scipy.stats import chi2


quantile_chi2_half = chi2.ppf(1 - alpha / 2, n - k)
quantile_chi2_one_and_half = chi2.ppf(alpha / 2, n - k)

quantile_chi2_half, quantile_chi2_one_and_half

(116.98907954358143, 64.79336148515908)

Доверительные интервалы для дисперсии: 


In [21]:
left = rss(predicted_price, price) / quantile_chi2_half
right = rss(predicted_price, price) / quantile_chi2_one_and_half

left, right

(11122.260738034824, 20082.042609943066)

In [22]:
np.sqrt(left), np.sqrt(right)

(105.46212940214522, 141.71112380453084)

А теперь посчитаем статистический тест (t-тест), и узнаем, влияют ли коэффициенты (он проверяет, что $H_0$ коэфф = 0 и не влияет. Если оказалось, что $\frac{\hat{\theta}_i}{se(i)} > t_{1-\frac{\alpha}{2}}$, то отвергаем $H_0$ ):

In [23]:
test_value = t.ppf(1 - alpha / 2, n - k)

$\frac{\hat{\theta}_i}{se(\hat{\theta}_i)} > t$, где $se$ --- стандартная ошибка

In [24]:
def check_coeff(pos, test_value):
    if theta_hat[pos] / np.sqrt(get_j(pos)) > test_value: 
        return 1
    else:
        return 0

check_coeff(3, test_value)

1

Мощность --- влияет

In [25]:
check_coeff(2, test_value)

0

Расход в городе --- не влияет

In [26]:
check_coeff(1, test_value) == check_coeff(2, test_value)

True

Они оба не влияют => $H_0$ выполнена

# Task 2


Требуется проверить гипотезу о равенстве средних на каждом уровне фактора с помощью модели однофакторного дисперсионного анализа.


## Calculate data


In [27]:
import pandas as pd
import numpy as np

df = pd.read_csv("iris.csv")
df["TotalArea"] = df["Sepal.Length"] * df["Sepal.Width"] + df["Petal.Length"] * df["Petal.Width"]
display(df)

splitted = np.array(list(map(lambda x: x[1], df.groupby("Species")["TotalArea"])))
splitted

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species   
0             5.1          3.5           1.4          0.2     setosa  \
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     TotalArea  
0        18.13  
1        14.98  
2        15.30  
3        14.56  
4        18.28  
..         ...  
145      32.06  
146      25.25  
147      29.90  
148      33.50  
149      26.88  

[150 rows x 6 columns]

array([[18.13, 14.98, 15.3 , 14.56, 18.28, 21.74, 16.06, 17.3 , 13.04,
        15.34, 20.28, 16.64, 14.54, 13.01, 23.44, 25.68, 21.58, 18.27,
        22.17, 19.83, 18.7 , 19.47, 16.76, 17.68, 16.7 , 15.32, 17.64,
        18.5 , 17.96, 15.36, 15.2 , 18.96, 21.47, 23.38, 15.49, 16.24,
        19.51, 17.78, 13.46, 17.64, 17.89, 10.74, 14.34, 18.46, 20.14,
        14.82, 19.7 , 15.  , 19.91, 16.78],
       [28.98, 27.23, 28.74, 17.85, 25.1 , 21.81, 28.31, 15.06, 25.12,
        19.5 , 13.5 , 24.  , 17.2 , 24.27, 20.92, 26.93, 23.55, 19.76,
        20.39, 18.29, 27.52, 22.28, 23.1 , 22.72, 24.15, 25.96, 25.76,
        28.6 , 24.15, 18.32, 17.38, 16.9 , 20.34, 24.36, 22.95, 27.6 ,
        27.82, 20.21, 22.13, 18.95, 19.58, 24.74, 19.88, 14.8 , 20.58,
        22.14, 21.99, 23.57, 16.05, 21.29],
       [35.79, 25.35, 33.69, 28.35, 32.26, 36.66, 19.9 , 32.51, 27.19,
        41.17, 31.  , 27.35, 31.95, 24.25, 28.48, 32.67, 29.4 , 44.  ,
        35.89, 20.7 , 35.19, 25.48, 34.96, 25.83, 34.08, 33.

## Формулировка гипотезы

$H_0$: Средняя площадь чашелистика + цветка равна у разных подвидов ириса

$H_1$: Средняя площадь чашелистика + цветка отличается у разных подвидов ириса

### Проверка библиотечным методом


In [28]:
from scipy.stats import f_oneway

f_oneway(*splitted)

F_onewayResult(statistic=133.29723648348485, pvalue=9.540732260908254e-34)

$\text{p-value} \ \ll 0.05 \Rightarrow H_0 \ \text{опровергнута в пользу} \ H_1$ 

### Реализация


In [29]:
from scipy.special import betainc

def anova(data: np.ndarray):
    I = data.size
    J = len(data)
    m = data.mean()
    s = data.var()
    
    def calc_SSBetweenGroups(data):
        l = 0
        for group in data:
            l += group.sum() ** 2 / len(group)  
        
        r = data.sum() ** 2 / I
        
        return l - r
        
    def calc_SSInGroups(data):
        l = (data ** 2).sum()
        
        r = 0
        for group in data:
            r += group.sum() ** 2 / len(group)  
        
        return l - r
    
    def f_cdf(x, a, b):
        return betainc(a / 2, b / 2, a * x / (a * x + b))
    
    SSBetweenGroups = calc_SSBetweenGroups(data)
    SSInGroups = calc_SSInGroups(data)
    
    DFBetweenGroups = J - 1
    DFInGroups = I - J

    MSBetweenGroups = SSBetweenGroups / DFBetweenGroups
    MSInGroups = SSInGroups / DFInGroups
    
    F = MSBetweenGroups / MSInGroups
    p_value = 1 - f_cdf(F, DFBetweenGroups, DFInGroups)
    return {
        "F-statistic": F,
        "p-value": p_value,
    }

anova(splitted)

{'F-statistic': 133.29723648348494, 'p-value': 1.1102230246251565e-16}

Мы видим, что значение p-value значительно меньше 0.05, таким образом, гипотеза $H_0$ опровергается, и мы говорим, что площадь не может не зависеть от сорта ириса.